### ISSUE TITLE
confusing with "merging" behavior. 

### ISSUE THREAD

**Issue by xtavras** [jlambert121/jlambert121-yum#23]
Hello,

I have problem with this module that merging doesn't really work for me, only the last match will applied instead of merging.

I have this repo in **common.yaml**
```
yum::repos:
  public_ol6_addons:
    descr: "Oracle Linux $releasever Add ons ($basearch)"
    baseurl: "http://yum.oracle.com/repo/OracleLinux/OL6/addons/$basearch/"
    gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle"
```
and specific repo in **fqdn.yaml**
```
yum::repos:
  nginx:
    descr: "Nginx official repo"
    baseurl: "http://nginx.org/packages/rhel/6/$basearch/"
    gpgcheck: 0

```
the problem is, that only "nginx" repo will applied. I have ":merge_behavior: deeper" in my hiera.yaml and other modules such "apt" or "sudo" working just fine with merging.
